---

version: '3'
services:
  deploy:
    container_name: automium-service-kubernetes-dev
    image: automium-service-kubernetes-dev
    build:
      context: .
    volumes:
      - "/tmp/${NAME}_terraform:/usr/src/provisioner/.terraform"
