---

- name: copy-cert | create ssl/etcd folder
  file:
    path: /etc/ssl/etcd
    state: directory
    mode: 0755

- name: copy-cert | create ssl/etcd/ssl folder
  file:
    path: /etc/ssl/etcd/ssl
    state: directory
    mode: 0755

- name: copy-cert | copy ca certificate and ca key on etcd node
  shell: rsync -e "ssh -o StrictHostKeyChecking=no" -avP root@{{ cluster_name }}-etcd.service.automium.consul:/etc/ssl/etcd/ssl/{{ item }} /etc/ssl/etcd/ssl/
  with_items:
    - ca-key.pem
    - ca.pem
  when:
    - etcd == "true"
  tags: others

- name: copy-cert | create kubernetes folder
  file:
    path: /etc/kubernetes/
    state: directory
    mode: 0755

- name: copy-cert | create kubernetes/ssl folder
  file:
    path: /etc/kubernetes/ssl
    state: directory
    mode: 0755

- name: copy-cert | copy kubernetes node certs
  shell: rsync -e "ssh -o StrictHostKeyChecking=no" -avP root@{{ cluster_name }}-kube-master.service.automium.consul:/etc/kubernetes/ssl/{{ item }} /etc/kubernetes/ssl/
  with_items:
    - front-proxy-ca.crt
  when:
    - node == "true"

- name: copy-cert | copy kubernetes master certs
  shell: rsync -e "ssh -o StrictHostKeyChecking=no" -avP root@{{ cluster_name }}-kube-master.service.automium.consul:/etc/kubernetes/ssl/{{ item }} /etc/kubernetes/ssl/
  with_items:
    - ca.crt
    - ca.key
    - sa.key
    - sa.pub
  when:
    - master == "true"
  tags: others
